### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by alexander-dubinski** [huraji/book-rating-system#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All code if valid and seems to work as expected.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ All requirements met.
 
### Criteria 3: Software Architecture
* _Score Level:_ All classes constructed well and in line with best practices.
* _Comment(s):_
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
* _Comment(s):_  Python features used well
 
### Overall Score: 16/16
Excellent job! One of the best ones I have seen, keep it up!

**Comment by debonx** [comment]
Thank you so much!
